// USER REDUCER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USERS';
export const LOADING_USER = 'LOADING_USER';
export const SET_USER_DATA = 'SET_USER_DATA';
export const NOTIFICATION_MANAGE = 'NOTIFICATION_MANAGE';
export const MAKE_NOTIFICATIONS_READ = 'MAKE_NOTIFICATIONS_READ';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_FALSE = "PASSWORD_RESET_FALSE";
export const SET_USER_ERRORS = "SET_USER_ERRORS";
export const CLEAR_USER_ERRORS = "CLEAR_USER_ERRORS";
export const STOP_USER_LOADING = "STOP_USER_LOADING";
export const SET_USER_IMAGE = 'SET_USER_IMAGE';
export const UNSET_USER_IMAGE = 'UNSET_USER_IMAGE';

// UI REDUCERS
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// DATA REDUCERS
export const SET_SCREAMS = 'SET_SCREAMS';
export const LOADING_DATA = 'LOADING_DATA';
export const LIKE_SCREAM = 'LIKE_SCREAM';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';
export const ADD_SCREAM = 'ADD_SCREAM';
export const DELETE_SCREAM = 'DELETE_SCREAM';
export const UPDATE_SCREAM_IMAGE = 'UPDATE_SCREAM_IMAGE';
export const SET_COMMENT = 'SET_COMMENT';
export const SET_SCREAM = 'SET_SCREAM';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const MANAGE_COMMENTS = 'MANAGE_COMMENTS';
export const SET_SCREAM_ERRORS = 'SET_SCREAM_ERRORS';
export const CLEAR_SCREAM_ERRORS = 'CLEAR_SCREAM_ERRORS';
export const SCREAM_LOADING = "SCREAM_LOADING";

